/// Automatic Generated by Vesyla. Do not edit! ///

#pragma once

// Kernel section indexing table: (start, size)
static const unsigned int kernel_index[][2] = {{0, 3}};

// Instruction indexing table: (row, column, start, size)
static const unsigned int instr_index[][4] = {
    {2, 0, 0, 13}, {1, 0, 13, 26}, {0, 0, 39, 12}};

// Instruction data array: 32-bit hex formatted instructions stored
// continuously.
static const unsigned int instr_data[] = {
    0x1000000E, 0xD0220008, 0x20004000, 0x1000001C, 0xE1000060, 0x81C01040,
    0xE1000020, 0x81401040, 0xE2000040, 0x82801040, 0x20004002, 0x2000A001,
    0x10000001, 0x00000000, 0xE3000000, 0x8301F040, 0xE1000020, 0x8141F040,
    0xE2000020, 0x8241F040, 0xE2000040, 0x82801041, 0xB40E0000, 0xE1000040,
    0x81801041, 0xC0105000, 0xC0149400, 0xC00D0C00, 0xD022000C, 0xD0060100,
    0x20005000, 0x21004001, 0x20004002, 0x20022001, 0x20001003, 0x1000001C,
    0xE3000060, 0x83C01040, 0x20008003, 0x10000002, 0x00000000, 0x10000007,
    0xE2000060, 0x82C03040, 0xE1000040, 0x81803040, 0xE1000000, 0x81001080,
    0x81041040, 0xD0040100, 0x20054000, 0x20008002, 0x10000024, 0x00000000};
