name: 'Check SST Installation'
description: 'Checks if SST Core and Elements are already installed'

inputs:
  sst-core-home:
    description: 'Path to SST Core installation'
    required: true
  sst-elements-home:
    description: 'Path to SST Elements installation'
    required: true

outputs:
  sst_installed:
    description: 'Whether SST is already installed'
    value: ${{ steps.check-sst.outputs.sst_installed }}

runs:
  using: 'composite'
  steps:
    - id: check-sst
      shell: bash
      run: |
        if [[ -d "${{ inputs.sst-core-home }}/bin" ]]; then
          echo "SST installation found in cache"
          echo "sst_installed=true" >> $GITHUB_OUTPUT
        else
          echo "No SST installation found, will install"
          echo "sst_installed=false" >> $GITHUB_OUTPUT
        fi