[package]
name = "vs-testcase"
version = "0.1.0"
edition = "2021"

# targets
[[bin]]
name = "vs-testcase"
path = "src/main.rs"


# Dependencies can be added here. For example:
[dependencies]
log = "0.4.14"
env_logger = "0.10.0"
argparse = "0.2.0"
glob = "0.3.0"
chrono = "0.4.19"