[package]
name = "vs-entry"
version = "0.1.0"
edition = "2021"

# targets
[[bin]]
name = "vs-entry"
path = "src/main.rs"


# Dependencies can be added here. For example:
[dependencies]
argparse = "0.2.0"
log = "0.4.14"
env_logger = "0.10.0"
rand = "0.8.4"
regex = "1.8.5"