function(add_component COMPONENT_TYPE COMPONENT_NAME)

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set(CMAKE_SHARED_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/share/${PROJECT_NAME})
set(INSTALL_ARCHIVE_OUTPUT_DIRECTORY lib)
set(INSTALL_LIBRARY_OUTPUT_DIRECTORY lib)
set(INSTALL_RUNTIME_OUTPUT_DIRECTORY bin)
set(INSTALL_SHARED_OUTPUT_DIRECTORY share/${PROJECT_NAME})

set(CURRENT_SUBPROJECT_NAME "vs-component-${COMPONENT_TYPE}-${COMPONENT_NAME}")
set(CMAKE_COMPONENTS_OUTPUT_DIRECTORY ${CMAKE_SHARED_OUTPUT_DIRECTORY}/components/${COMPONENT_TYPE}/${COMPONENT_NAME})
set(INSTALL_COMPONENTS_OUTPUT_DIRECTORY ${INSTALL_SHARED_OUTPUT_DIRECTORY}/components/${COMPONENT_TYPE}/${COMPONENT_NAME})

find_program(CARGO_EXECUTABLE cargo)
find_program(RUSTC_EXECUTABLE rustc)

message(STATUS "COMPONENT_TYPE: ${COMPONENT_TYPE}")

if(${COMPONENT_TYPE} STREQUAL "resources")

   set(FILE_LIST arch.json isa.json rtl.sv)
   install(FILES ${FILE_LIST} DESTINATION ${INSTALL_COMPONENTS_OUTPUT_DIRECTORY})
   file(COPY ${FILE_LIST} DESTINATION ${CMAKE_COMPONENTS_OUTPUT_DIRECTORY})

   # timing_model
   file(GLOB TIMING_MODEL_SRC "timing_model/src/*.rs")
   add_custom_command(
      OUTPUT ${CMAKE_COMPONENTS_OUTPUT_DIRECTORY}/timing_model
      DEPENDS ${TIMING_MODEL_SRC}
      COMMAND mkdir -p ${CMAKE_RUNTIME_OUTPUT_DIRECTORY} &&
      mkdir -p ${CMAKE_BINARY_DIR}/cargo/${CURRENT_SUBPROJECT_NAME} &&
      cargo build --release --target-dir=${CMAKE_BINARY_DIR}/cargo/${CURRENT_SUBPROJECT_NAME} &&
      cp -p ${CMAKE_BINARY_DIR}/cargo/${CURRENT_SUBPROJECT_NAME}/release/timing_model ${CMAKE_COMPONENTS_OUTPUT_DIRECTORY}
      WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/timing_model
   )
   add_custom_target(gen-${CURRENT_SUBPROJECT_NAME} ALL DEPENDS ${CMAKE_COMPONENTS_OUTPUT_DIRECTORY}/timing_model)
   install(PROGRAMS ${CMAKE_COMPONENTS_OUTPUT_DIRECTORY}/timing_model DESTINATION ${INSTALL_COMPONENTS_OUTPUT_DIRECTORY})

elseif(${COMPONENT_TYPE} STREQUAL "controllers")

   set(FILE_LIST arch.json isa.json rtl.sv)
   install(FILES ${FILE_LIST} DESTINATION ${INSTALL_COMPONENTS_OUTPUT_DIRECTORY})
   file(COPY ${FILE_LIST} DESTINATION ${CMAKE_COMPONENTS_OUTPUT_DIRECTORY})


elseif(${COMPONENT_TYPE} STREQUAL "cells")

   set(FILE_LIST arch.json isa.json rtl.sv)
   install(FILES ${FILE_LIST} DESTINATION ${INSTALL_COMPONENTS_OUTPUT_DIRECTORY})
   file(COPY ${FILE_LIST} DESTINATION ${CMAKE_COMPONENTS_OUTPUT_DIRECTORY})

endif()

endfunction()

MACRO(SUBDIRLIST result curdir)
  FILE(GLOB children RELATIVE ${curdir} ${curdir}/*)
  SET(dirlist "")
  FOREACH(child ${children})
    IF(IS_DIRECTORY ${curdir}/${child})
      LIST(APPEND dirlist ${child})
    ENDIF()
  ENDFOREACH()
  SET(${result} ${dirlist})
ENDMACRO()

function(add_all_subdirs)
   SUBDIRLIST(SUBDIRS ${CMAKE_CURRENT_SOURCE_DIR})
   FOREACH(subdir ${SUBDIRS})
      ADD_SUBDIRECTORY(${subdir})
   ENDFOREACH()
endfunction()
