# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataBase.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DataBase.proto',
  package='vs.manas.dt',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x44\x61taBase.proto\x12\x0bvs.manas.dt\"b\n\x08\x44\x61taBase\x12(\n\x03isa\x18\x01 \x01(\x0b\x32\x1b.vs.manas.dt.InstructionSet\x12,\n\x03pkg\x18\x02 \x01(\x0b\x32\x1f.vs.manas.dt.InstructionPackage\"\x97\x01\n\x0eInstructionSet\x12\x10\n\x08platform\x18\x01 \x01(\t\x12\x16\n\x0einstr_bitwidth\x18\x02 \x01(\x05\x12\x1b\n\x13instr_code_bitwidth\x18\x03 \x01(\x05\x12>\n\x15instruction_templates\x18\x04 \x03(\x0b\x32\x1f.vs.manas.dt.InstrctionTemplate\"{\n\x12InstrctionTemplate\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x10\n\x08machines\x18\x03 \x03(\t\x12\x37\n\x11segment_templates\x18\x04 \x03(\x0b\x32\x1c.vs.manas.dt.SegmentTemplate\"\x95\x01\n\x0fSegmentTemplate\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x62itwidth\x18\x02 \x01(\x05\x12\x11\n\tis_signed\x18\x03 \x01(\x08\x12\x13\n\x0b\x64\x65\x66\x61ult_val\x18\x04 \x01(\x05\x12)\n\tverbo_map\x18\x05 \x03(\x0b\x32\x16.vs.manas.dt.IntStrMap\x12\x0f\n\x07\x63omment\x18\x06 \x01(\t\"~\n\x12InstructionPackage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x10\n\x08platform\x18\x03 \x01(\t\x12\x37\n\x11instruction_lists\x18\x04 \x03(\x0b\x32\x1c.vs.manas.dt.InstructionList\"P\n\x0fInstructionList\x12\r\n\x05label\x18\x01 \x01(\t\x12.\n\x0cinstructions\x18\x02 \x03(\x0b\x32\x18.vs.manas.dt.Instruction\"\xa2\x01\n\x0bInstruction\x12\x0c\n\x04name\x18\x01 \x01(\t\x12)\n\tvalue_map\x18\x02 \x03(\x0b\x32\x16.vs.manas.dt.StrIntMap\x12,\n\x0cint_info_map\x18\x03 \x03(\x0b\x32\x16.vs.manas.dt.StrIntMap\x12,\n\x0cstr_info_map\x18\x04 \x03(\x0b\x32\x16.vs.manas.dt.StrStrMap\"%\n\tStrIntMap\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\x05\"%\n\tStrStrMap\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\t\"%\n\tIntStrMap\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x0b\n\x03val\x18\x02 \x01(\tb\x06proto3'
)




_DATABASE = _descriptor.Descriptor(
  name='DataBase',
  full_name='vs.manas.dt.DataBase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isa', full_name='vs.manas.dt.DataBase.isa', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pkg', full_name='vs.manas.dt.DataBase.pkg', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=129,
)


_INSTRUCTIONSET = _descriptor.Descriptor(
  name='InstructionSet',
  full_name='vs.manas.dt.InstructionSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='platform', full_name='vs.manas.dt.InstructionSet.platform', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instr_bitwidth', full_name='vs.manas.dt.InstructionSet.instr_bitwidth', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instr_code_bitwidth', full_name='vs.manas.dt.InstructionSet.instr_code_bitwidth', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instruction_templates', full_name='vs.manas.dt.InstructionSet.instruction_templates', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=283,
)


_INSTRCTIONTEMPLATE = _descriptor.Descriptor(
  name='InstrctionTemplate',
  full_name='vs.manas.dt.InstrctionTemplate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='vs.manas.dt.InstrctionTemplate.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='vs.manas.dt.InstrctionTemplate.code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='machines', full_name='vs.manas.dt.InstrctionTemplate.machines', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='segment_templates', full_name='vs.manas.dt.InstrctionTemplate.segment_templates', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=408,
)


_SEGMENTTEMPLATE = _descriptor.Descriptor(
  name='SegmentTemplate',
  full_name='vs.manas.dt.SegmentTemplate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='vs.manas.dt.SegmentTemplate.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bitwidth', full_name='vs.manas.dt.SegmentTemplate.bitwidth', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_signed', full_name='vs.manas.dt.SegmentTemplate.is_signed', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='default_val', full_name='vs.manas.dt.SegmentTemplate.default_val', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='verbo_map', full_name='vs.manas.dt.SegmentTemplate.verbo_map', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comment', full_name='vs.manas.dt.SegmentTemplate.comment', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=411,
  serialized_end=560,
)


_INSTRUCTIONPACKAGE = _descriptor.Descriptor(
  name='InstructionPackage',
  full_name='vs.manas.dt.InstructionPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='vs.manas.dt.InstructionPackage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='vs.manas.dt.InstructionPackage.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='platform', full_name='vs.manas.dt.InstructionPackage.platform', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instruction_lists', full_name='vs.manas.dt.InstructionPackage.instruction_lists', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=562,
  serialized_end=688,
)


_INSTRUCTIONLIST = _descriptor.Descriptor(
  name='InstructionList',
  full_name='vs.manas.dt.InstructionList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='vs.manas.dt.InstructionList.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instructions', full_name='vs.manas.dt.InstructionList.instructions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=690,
  serialized_end=770,
)


_INSTRUCTION = _descriptor.Descriptor(
  name='Instruction',
  full_name='vs.manas.dt.Instruction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='vs.manas.dt.Instruction.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_map', full_name='vs.manas.dt.Instruction.value_map', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int_info_map', full_name='vs.manas.dt.Instruction.int_info_map', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='str_info_map', full_name='vs.manas.dt.Instruction.str_info_map', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=773,
  serialized_end=935,
)


_STRINTMAP = _descriptor.Descriptor(
  name='StrIntMap',
  full_name='vs.manas.dt.StrIntMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='vs.manas.dt.StrIntMap.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='val', full_name='vs.manas.dt.StrIntMap.val', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=937,
  serialized_end=974,
)


_STRSTRMAP = _descriptor.Descriptor(
  name='StrStrMap',
  full_name='vs.manas.dt.StrStrMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='vs.manas.dt.StrStrMap.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='val', full_name='vs.manas.dt.StrStrMap.val', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=976,
  serialized_end=1013,
)


_INTSTRMAP = _descriptor.Descriptor(
  name='IntStrMap',
  full_name='vs.manas.dt.IntStrMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='vs.manas.dt.IntStrMap.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='val', full_name='vs.manas.dt.IntStrMap.val', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1015,
  serialized_end=1052,
)

_DATABASE.fields_by_name['isa'].message_type = _INSTRUCTIONSET
_DATABASE.fields_by_name['pkg'].message_type = _INSTRUCTIONPACKAGE
_INSTRUCTIONSET.fields_by_name['instruction_templates'].message_type = _INSTRCTIONTEMPLATE
_INSTRCTIONTEMPLATE.fields_by_name['segment_templates'].message_type = _SEGMENTTEMPLATE
_SEGMENTTEMPLATE.fields_by_name['verbo_map'].message_type = _INTSTRMAP
_INSTRUCTIONPACKAGE.fields_by_name['instruction_lists'].message_type = _INSTRUCTIONLIST
_INSTRUCTIONLIST.fields_by_name['instructions'].message_type = _INSTRUCTION
_INSTRUCTION.fields_by_name['value_map'].message_type = _STRINTMAP
_INSTRUCTION.fields_by_name['int_info_map'].message_type = _STRINTMAP
_INSTRUCTION.fields_by_name['str_info_map'].message_type = _STRSTRMAP
DESCRIPTOR.message_types_by_name['DataBase'] = _DATABASE
DESCRIPTOR.message_types_by_name['InstructionSet'] = _INSTRUCTIONSET
DESCRIPTOR.message_types_by_name['InstrctionTemplate'] = _INSTRCTIONTEMPLATE
DESCRIPTOR.message_types_by_name['SegmentTemplate'] = _SEGMENTTEMPLATE
DESCRIPTOR.message_types_by_name['InstructionPackage'] = _INSTRUCTIONPACKAGE
DESCRIPTOR.message_types_by_name['InstructionList'] = _INSTRUCTIONLIST
DESCRIPTOR.message_types_by_name['Instruction'] = _INSTRUCTION
DESCRIPTOR.message_types_by_name['StrIntMap'] = _STRINTMAP
DESCRIPTOR.message_types_by_name['StrStrMap'] = _STRSTRMAP
DESCRIPTOR.message_types_by_name['IntStrMap'] = _INTSTRMAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataBase = _reflection.GeneratedProtocolMessageType('DataBase', (_message.Message,), {
  'DESCRIPTOR' : _DATABASE,
  '__module__' : 'DataBase_pb2'
  # @@protoc_insertion_point(class_scope:vs.manas.dt.DataBase)
  })
_sym_db.RegisterMessage(DataBase)

InstructionSet = _reflection.GeneratedProtocolMessageType('InstructionSet', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUCTIONSET,
  '__module__' : 'DataBase_pb2'
  # @@protoc_insertion_point(class_scope:vs.manas.dt.InstructionSet)
  })
_sym_db.RegisterMessage(InstructionSet)

InstrctionTemplate = _reflection.GeneratedProtocolMessageType('InstrctionTemplate', (_message.Message,), {
  'DESCRIPTOR' : _INSTRCTIONTEMPLATE,
  '__module__' : 'DataBase_pb2'
  # @@protoc_insertion_point(class_scope:vs.manas.dt.InstrctionTemplate)
  })
_sym_db.RegisterMessage(InstrctionTemplate)

SegmentTemplate = _reflection.GeneratedProtocolMessageType('SegmentTemplate', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTTEMPLATE,
  '__module__' : 'DataBase_pb2'
  # @@protoc_insertion_point(class_scope:vs.manas.dt.SegmentTemplate)
  })
_sym_db.RegisterMessage(SegmentTemplate)

InstructionPackage = _reflection.GeneratedProtocolMessageType('InstructionPackage', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUCTIONPACKAGE,
  '__module__' : 'DataBase_pb2'
  # @@protoc_insertion_point(class_scope:vs.manas.dt.InstructionPackage)
  })
_sym_db.RegisterMessage(InstructionPackage)

InstructionList = _reflection.GeneratedProtocolMessageType('InstructionList', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUCTIONLIST,
  '__module__' : 'DataBase_pb2'
  # @@protoc_insertion_point(class_scope:vs.manas.dt.InstructionList)
  })
_sym_db.RegisterMessage(InstructionList)

Instruction = _reflection.GeneratedProtocolMessageType('Instruction', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUCTION,
  '__module__' : 'DataBase_pb2'
  # @@protoc_insertion_point(class_scope:vs.manas.dt.Instruction)
  })
_sym_db.RegisterMessage(Instruction)

StrIntMap = _reflection.GeneratedProtocolMessageType('StrIntMap', (_message.Message,), {
  'DESCRIPTOR' : _STRINTMAP,
  '__module__' : 'DataBase_pb2'
  # @@protoc_insertion_point(class_scope:vs.manas.dt.StrIntMap)
  })
_sym_db.RegisterMessage(StrIntMap)

StrStrMap = _reflection.GeneratedProtocolMessageType('StrStrMap', (_message.Message,), {
  'DESCRIPTOR' : _STRSTRMAP,
  '__module__' : 'DataBase_pb2'
  # @@protoc_insertion_point(class_scope:vs.manas.dt.StrStrMap)
  })
_sym_db.RegisterMessage(StrStrMap)

IntStrMap = _reflection.GeneratedProtocolMessageType('IntStrMap', (_message.Message,), {
  'DESCRIPTOR' : _INTSTRMAP,
  '__module__' : 'DataBase_pb2'
  # @@protoc_insertion_point(class_scope:vs.manas.dt.IntStrMap)
  })
_sym_db.RegisterMessage(IntStrMap)


# @@protoc_insertion_point(module_scope)
