name: Create AppImage

on:
  workflow_call:
    outputs:
      version:
        description: "Version from the built vesyla appimage"
        value: ${{ jobs.build.steps.check-version.outputs.version }}

jobs:
  run-cargo-tests:
    name: Run Cargo tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install bender
        run: |
          curl --proto '=https' --tlsv1.2 https://pulp-platform.github.io/bender/init -sSf | sh
          mkdir -p $HOME/.local/bin
          mv bender $HOME/.local/bin/.
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Check bender installation
        run: bender --version

      - name: Run Cargo tests
        run: |
          cd modules
          RUST_BACKTRACE=1 cargo test --all

  build:
    name: Build AppImage
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.check-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          make all
          make install

      - name: Check version
        id: check-version
        run: |
          version=$(./vesyla --version | grep '^vesyla ' | awk '{print $2}')
          echo "$version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Upload built artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: vesyla-${{ github.sha }}
          path: ./vesyla
          overwrite: true
