name: Create AppImage

on:
  workflow_call:

jobs:
  build:
    name: Build AppImage
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          ./scripts/install_dependencies.sh
          ./scripts/make_appimage.sh

      - name: Upload built artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: vesyla-${{ github.sha }}
          path: ./vesyla
          overwrite: true
