name: PR workflow

on:
  pull_request:

jobs:
  ci-build-vesyla:
    name: Build Vesyla
    uses: ./.github/workflows/ci-build-appimage.yml
    secrets: inherit

  debug-version:
    name: Debug version output
    needs: ci-build-vesyla
    runs-on: ubuntu-22.04
    steps:
      - run: echo ${{ needs.ci-build-vesyla.outputs.version }}

  ci-run-tests:
    name: Run DRRA Tests
    uses: ./.github/workflows/ci-run-tests.yml
    needs: ci-build-vesyla
    secrets: inherit
    with:
      version: ${{ needs.ci-build-vesyla.outputs.version }}
